# Generated by Django 2.2 on 2021-04-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='catagory',
            field=models.CharField(default='Garden', max_length=45),
            preserve_default=False,
        ),
    ]
