# Generated by Django 2.2 on 2021-04-23 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper_app', '0002_job_catagory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='catagory',
        ),
    ]
