# Generated by Django 2.2 on 2021-04-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper_app', '0003_remove_job_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='catagory',
            field=models.CharField(default='None', max_length=50),
            preserve_default=False,
        ),
    ]
