# Generated by Django 2.2 on 2021-04-26 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper_app', '0004_job_catagory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='catagory',
            new_name='category',
        ),
    ]
