# Generated by Django 2.2 on 2021-04-26 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helper_app', '0006_job_this_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='this_user',
        ),
        migrations.AddField(
            model_name='job',
            name='other_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='other_users', to='helper_app.User'),
            preserve_default=False,
        ),
    ]
